apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: myapp
  namespace: flux-system
spec:
  targetNamespace: myapp
  interval: 1m
  path: "./"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
